import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
=========================================================
  OBSIDIAN AGENT PLUGIN
  AI-enhanced assistant for Obsidian
  
  Version: ${getVersion()}
  Author: B0LK13
  License: MIT
  Repository: https://github.com/B0LK13/obsidian-agent
=========================================================
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = (process.argv[2] === 'production');

function getVersion() {
    try {
        const manifest = JSON.parse(fs.readFileSync('./manifest.json', 'utf8'));
        return manifest.version;
    } catch {
        return '1.0.0';
    }
}

/**
 * Report CSS minification savings for production builds.
 * This function calculates and reports potential size savings without modifying files.
 * Actual CSS minification is performed by the package script during distribution.
 */
async function reportCSSMinificationSavings() {
    const cssFiles = ['styles.css', 'styles-enhanced.css'];
    const results = [];
    
    for (const file of cssFiles) {
        if (!fs.existsSync(file)) {
            continue;
        }
        
        try {
            const css = fs.readFileSync(file, 'utf8');
            const result = await esbuild.transform(css, {
                loader: 'css',
                minify: true
            });
            
            const originalSize = Buffer.byteLength(css, 'utf8');
            const minifiedSize = Buffer.byteLength(result.code, 'utf8');
            const savings = ((originalSize - minifiedSize) / originalSize * 100).toFixed(1);
            
            results.push({
                file,
                original: originalSize,
                minified: minifiedSize,
                savings
            });
        } catch (error) {
            console.warn(`  ⚠️ Could not analyze ${file}: ${error.message}`);
        }
    }
    
    return results;
}

async function build() {
    const context = await esbuild.context({
        banner: {
            js: banner,
        },
        entryPoints: ['main.ts'],
        bundle: true,
        external: [
            'obsidian',
            'electron',
            '@codemirror/autocomplete',
            '@codemirror/collab',
            '@codemirror/commands',
            '@codemirror/language',
            '@codemirror/lint',
            '@codemirror/search',
            '@codemirror/state',
            '@codemirror/view',
            '@lezer/common',
            '@lezer/highlight',
            '@lezer/lr',
            ...builtins
        ],
        format: 'cjs',
        target: 'es2018',
        logLevel: "info",
        sourcemap: prod ? false : 'inline',
        treeShaking: true,
        minify: prod,
        minifyWhitespace: prod,
        minifyIdentifiers: prod,
        minifySyntax: prod,
        outfile: 'main.js',
        metafile: prod,
        platform: 'browser',
        define: prod ? {
            'process.env.NODE_ENV': '"production"',
            'process.env.DEBUG': 'false'
        } : {
            'process.env.NODE_ENV': '"development"',
            'process.env.DEBUG': 'true'
        },
    });

    if (prod) {
        console.log('\n🔨 Building for production...\n');
        const result = await context.rebuild();
        
        // Log bundle size
        if (result.metafile) {
            const outputs = result.metafile.outputs;
            for (const [file, info] of Object.entries(outputs)) {
                const sizeKB = (info.bytes / 1024).toFixed(2);
                console.log(`📦 ${path.basename(file)}: ${sizeKB} KB`);
            }
            
            // Write metafile for analysis
            fs.writeFileSync('build-meta.json', JSON.stringify(result.metafile, null, 2));
            console.log('\n📊 Build metadata written to build-meta.json');
        }
        
        // Report CSS minification savings (actual minification happens during packaging)
        console.log('\n🎨 CSS Minification Preview...');
        const cssResults = await reportCSSMinificationSavings();
        for (const result of cssResults) {
            const originalKB = (result.original / 1024).toFixed(2);
            const minifiedKB = (result.minified / 1024).toFixed(2);
            console.log(`📦 ${result.file}: ${originalKB} KB → ${minifiedKB} KB (${result.savings}% reduction)`);
        }
        
        // Verify output
        if (fs.existsSync('main.js')) {
            const stats = fs.statSync('main.js');
            const sizeKB = (stats.size / 1024).toFixed(2);
            
            // Calculate total size
            let totalSize = stats.size;
            for (const result of cssResults) {
                totalSize += result.minified;
            }
            const totalKB = (totalSize / 1024).toFixed(2);
            
            console.log(`\n✅ Build successful!`);
            console.log(`   JavaScript: main.js (${sizeKB} KB)`);
            console.log(`   Total bundle: ${totalKB} KB`);
        }
        
        await context.dispose();
        process.exit(0);
    } else {
        console.log('👀 Watching for changes...');
        await context.watch();
    }
}

build().catch((err) => {
    console.error('❌ Build failed:', err);
    process.exit(1);
});
