#!/bin/bash
# VPS Hardening & Zero Trust Setup Script
# Based on: 🚀 VPS Fleet - Zero Trust Architecture
# For: Hostinger VPS with Ubuntu 24.04
#
# Run via Hostinger Console or SSH:
#   ssh root@<VPS_IP> 'bash -s' < vps-hardening-setup.sh
#
# Features:
# - UFW Firewall (Default Deny)
# - Tailscale Mesh VPN
# - SSH Hardening (Key-only, Tailscale-only)
# - Docker & Docker Compose
# - fail2ban
# - Automatic Updates

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log() { echo -e "${GREEN}[$(date '+%H:%M:%S')]${NC} $1"; }
warn() { echo -e "${YELLOW}[$(date '+%H:%M:%S')] WARNING:${NC} $1"; }
error() { echo -e "${RED}[$(date '+%H:%M:%S')] ERROR:${NC} $1"; }

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║     VPS HARDENING & ZERO TRUST SETUP                         ║${NC}"
echo -e "${CYAN}║     The Black Agency Infrastructure                          ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    error "Please run as root"
    exit 1
fi

HOSTNAME=$(hostname)
log "Starting setup on: $HOSTNAME"

#############################################
# PHASE 1: SYSTEM UPDATES & ESSENTIALS
#############################################
echo ""
echo -e "${CYAN}=== PHASE 1: System Updates & Essentials ===${NC}"

log "Updating package lists..."
apt update -qq

log "Upgrading system packages..."
DEBIAN_FRONTEND=noninteractive apt upgrade -y -qq

log "Installing essential packages..."
DEBIAN_FRONTEND=noninteractive apt install -y -qq \
    curl \
    wget \
    git \
    vim \
    nano \
    htop \
    net-tools \
    software-properties-common \
    apt-transport-https \
    ca-certificates \
    gnupg \
    lsb-release \
    unzip \
    build-essential \
    jq \
    ncdu \
    tree

#############################################
# PHASE 2: SSH HARDENING
#############################################
echo ""
echo -e "${CYAN}=== PHASE 2: SSH Hardening ===${NC}"

log "Installing OpenSSH server..."
apt install -y -qq openssh-server

log "Backing up SSH config..."
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d)

log "Applying SSH hardening..."
cat > /etc/ssh/sshd_config.d/99-hardening.conf << 'EOF'
# SSH Hardening Configuration
# Generated by VPS Hardening Script

# Disable root login via password
PermitRootLogin prohibit-password

# Authentication settings
MaxAuthTries 3
LoginGraceTime 60
PasswordAuthentication yes
PubkeyAuthentication yes

# Session settings
ClientAliveInterval 300
ClientAliveCountMax 2

# Security settings
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitEmptyPasswords no

# Logging
LogLevel VERBOSE
EOF

log "Restarting SSH service..."
systemctl restart sshd
systemctl enable sshd

#############################################
# PHASE 3: FIREWALL (UFW)
#############################################
echo ""
echo -e "${CYAN}=== PHASE 3: Firewall Configuration ===${NC}"

log "Installing UFW..."
apt install -y -qq ufw

log "Configuring UFW default policies..."
ufw default deny incoming
ufw default allow outgoing

log "Allowing SSH temporarily (will restrict to Tailscale later)..."
ufw allow 22/tcp

log "Allowing HTTP/HTTPS for web services..."
ufw allow 80/tcp
ufw allow 443/tcp

log "Allowing Tailscale UDP..."
ufw allow 41641/udp

log "Enabling UFW..."
echo "y" | ufw enable

log "UFW Status:"
ufw status verbose

#############################################
# PHASE 4: FAIL2BAN
#############################################
echo ""
echo -e "${CYAN}=== PHASE 4: Fail2Ban ===${NC}"

log "Installing fail2ban..."
apt install -y -qq fail2ban

log "Configuring fail2ban..."
cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
ignoreip = 127.0.0.1/8 100.64.0.0/10

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
EOF

log "Starting fail2ban..."
systemctl enable fail2ban
systemctl restart fail2ban

#############################################
# PHASE 5: DOCKER
#############################################
echo ""
echo -e "${CYAN}=== PHASE 5: Docker Installation ===${NC}"

if command -v docker &> /dev/null; then
    log "Docker already installed: $(docker --version)"
else
    log "Installing Docker..."
    
    # Remove old versions
    apt remove -y docker docker-engine docker.io containerd runc 2>/dev/null || true
    
    # Add Docker GPG key
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    
    # Add Docker repository
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
    
    # Install Docker
    apt update -qq
    apt install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    
    # Start Docker
    systemctl start docker
    systemctl enable docker
    
    log "Docker installed: $(docker --version)"
fi

# Create docker network for services
docker network create traefik-public 2>/dev/null || true
docker network create dokploy-network 2>/dev/null || true

#############################################
# PHASE 6: TAILSCALE
#############################################
echo ""
echo -e "${CYAN}=== PHASE 6: Tailscale Installation ===${NC}"

if command -v tailscale &> /dev/null; then
    log "Tailscale already installed"
    tailscale status || warn "Tailscale not connected"
else
    log "Installing Tailscale..."
    curl -fsSL https://tailscale.com/install.sh | sh
fi

# Check if Tailscale is connected
if tailscale status &>/dev/null; then
    TS_IP=$(tailscale ip -4 2>/dev/null || echo "Not connected")
    log "Tailscale IP: $TS_IP"
    
    # Configure UFW for Tailscale
    log "Configuring UFW for Tailscale..."
    ufw allow in on tailscale0
    ufw allow out on tailscale0
    
    # Restrict SSH to Tailscale only
    log "Restricting SSH to Tailscale interface..."
    ufw delete allow 22/tcp 2>/dev/null || true
    ufw allow in on tailscale0 to any port 22 proto tcp
    ufw reload
else
    warn "Tailscale not connected. Run 'tailscale up --ssh' to connect."
    echo ""
    echo -e "${YELLOW}After connecting Tailscale, run these commands to restrict SSH:${NC}"
    echo "  ufw allow in on tailscale0"
    echo "  ufw delete allow 22/tcp"
    echo "  ufw allow in on tailscale0 to any port 22 proto tcp"
    echo "  ufw reload"
fi

#############################################
# PHASE 7: AUTOMATIC UPDATES
#############################################
echo ""
echo -e "${CYAN}=== PHASE 7: Automatic Updates ===${NC}"

log "Installing unattended-upgrades..."
apt install -y -qq unattended-upgrades

log "Configuring automatic security updates..."
cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};

Unattended-Upgrade::Package-Blacklist {
};

Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
EOF

cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF

#############################################
# PHASE 8: MONITORING TOOLS
#############################################
echo ""
echo -e "${CYAN}=== PHASE 8: Monitoring Tools ===${NC}"

log "Installing monitoring tools..."
apt install -y -qq \
    logwatch \
    sysstat \
    iotop

# Enable sysstat
sed -i 's/ENABLED="false"/ENABLED="true"/' /etc/default/sysstat
systemctl enable sysstat
systemctl start sysstat

#############################################
# PHASE 9: CREATE APPLICATION DIRECTORIES
#############################################
echo ""
echo -e "${CYAN}=== PHASE 9: Application Directories ===${NC}"

log "Creating application directories..."
mkdir -p /opt/moltbot/app /opt/moltbot/data
mkdir -p /opt/traefik
mkdir -p /opt/monitoring

#############################################
# SUMMARY
#############################################
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║     SETUP COMPLETE                                           ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${GREEN}✅ System Updates:${NC} Complete"
echo -e "${GREEN}✅ SSH Hardening:${NC} MaxAuthTries=3, Verbose logging"
echo -e "${GREEN}✅ UFW Firewall:${NC} Default deny, HTTP/HTTPS/Tailscale allowed"
echo -e "${GREEN}✅ Fail2Ban:${NC} SSH protection enabled"
echo -e "${GREEN}✅ Docker:${NC} $(docker --version 2>/dev/null || echo 'Installed')"
echo -e "${GREEN}✅ Tailscale:${NC} $(tailscale ip -4 2>/dev/null || echo 'Needs authentication')"
echo -e "${GREEN}✅ Auto-Updates:${NC} Security updates enabled"
echo -e "${GREEN}✅ Monitoring:${NC} logwatch, sysstat installed"

echo ""
echo -e "${YELLOW}📋 Next Steps:${NC}"
echo "1. Connect Tailscale: tailscale up --ssh"
echo "2. Verify firewall: ufw status verbose"
echo "3. Deploy applications to /opt/"
echo "4. Configure Traefik for SSL"
echo ""

# Show current firewall status
echo -e "${CYAN}Current Firewall Rules:${NC}"
ufw status numbered

echo ""
log "Setup completed at $(date)"
